### ISSUE TITLE
We have NotANumber but need also Infinity?

### ISSUE THREAD

**Issue by ablaom** [ablaom/EarlyStopping.jl#23]
Something like `Infinity(exclude_negative=false)` ?

Currently `NotANumber` only catches `NaN`.

**Comment by ablaom** [comment]
On second thoughts, I think it's silly to have more than one of these. After all, one can already tailor `WithLossDo(f, stop_if_true=true)` to do all manner of less common things. So we just need the one method for the most common use-case, which is to catch `NaN`, `Inf` and `-Inf`. All solutions I can think of are breaking; we could:

1. Change `NotANumber` to catch all three but keep the name, or
2. Change `NotANumber` but change the name to ...? 

Thoughts anyone?

@OkonSamuel @jeremiedb @dmolina

**Comment by ablaom** [comment]
Related: https://github.com/Evovest/EvoTrees.jl/issues/84, https://github.com/alan-turing-institute/MLJBase.jl/pull/531

**Comment by jeremiedb** [comment]
Considering that 
```julia
julia> typeof(-Inf) <: Number
true
```

I'd favor option 2.  As for the name... something like `InvalidValue`? No strong opinion here!

**Comment by ablaom** [comment]
Yes, good point, thanks @jeremiedb

**Comment by ablaom** [comment]
@jeremiedb What about `OutOfBounds`?

**Comment by jeremiedb** [comment]
Isn't it subject to association with the notion of invalid indexing, a bit in the spirit `@inbounds`? Or maybe I'm just seeing problems everywhere :D

**Comment by ablaom** [comment]
Yes, you're right. Let's stick with `InvalidValue`, then.
